### ISSUE TITLE
Crash on some specific case of shuffling in stability. 

### ISSUE THREAD

**Issue by bachboss** [ChongWu-Biostat/prclust#1]
**Version:** 
- prclust = 1.2 (from CRAN), 
- R version 3.3.2 (2016-10-31) (also crash in version 3.3.0).

**Step to reproduce:**
I tried to run with `stability(..., n.times=100)` with `iris` data-set (file included).
The source code and data-set which reproduce the symptoms are attached here [(issue.zip)](https://github.com/ChongWu-Biostat/prclust/files/600450/issue.zip).

**Expected output:**
The algorithm runs successfully and returns result.

**Real output:**
The algorithm stops working with some specific shuffle of train/test in `stability` method.

**Note**
- I notified this problem while working with both `prclust` and `stability`. I tried to let the machine runfor hours but no such luck.
- I tried to add some debugging to the `stability` function, and it seems to crash at iteration 92 / 100. Not sure that is due to the data-set or some edge-case in `prclust_DCADMM`.

Attachment files:  [(issue.zip)](https://github.com/ChongWu-Biostat/prclust/files/600450/issue.zip).

**Comment by ChongWu-Biostat** [comment]
Thanks for your comments. I will debug it soon. Hope I can figure it out this week.
Thanks,
Chong

**Comment by bachboss** [comment]
Is there any update on this issue yet?

Thank you.

**Comment by ChongWu-Biostat** [comment]
Sorry. I am so busy these days and forget this issue. I will start debug it this week. Sorry about waiting.
Thanks,
Chong

**Comment by ChongWu-Biostat** [comment]
Please check the updated version of the package. I also added some other non-convex penalty, such as SCAD and MCP, for grouping penalty part.  Let me know if you have any other questions. You can download the newest version from github now or you can wait a few days and then download it from CRAN.

Thanks,
Chong
